n_centers_generated = 20
n_samples = 5000
n_samples_per_client = 100
n_features = 2
random_state = 42
merging_threshold = 4.0
visualize = False
verbose = False
n_iterations = 50
max_iterations_clustering = 50
n_clients = 12
clustering_methods = ["kmeans"] * (n_clients // 3) + ["mini_batch_kmeans"] * (n_clients // 3) + ["meanshift"] * (n_clients // 3)
# n_clusters = [8] * (n_clients // 3) + [8] * (n_clients // 3) + [None] * (n_clients // 3)
n_clusters = [5, 6, 7, 8, 5, 6, 7, 8, None, None, None, None]
density_aware_merging = True