n_clients = 6
n_clusters = [6, 7, 8, None, None, None]
clustering_methods = ["kmeans", "kmeans", "kmeans", "meanshift", "meanshift", "meanshift"]
n_centers_generated = 8
# n_clients = 3
# n_clusters = [None, 3, 3]
# clustering_methods = ["meanshift", "kmeans", "kmeans"]
# n_centers_generated = 6
n_samples_per_client = 400
n_features = 2
random_state = 42
merging_threshold = 4.0
visualize = True
